name: Build & Publish NPM Package

on:
  push:
    tags:
      - '**'

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  js_bindings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get the version
        id: version_info
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Update version in package.json
        env:
          SOURCE_TAG: ${{ steps.version_info.outputs.SOURCE_TAG }}
        run: |
          jq --arg VER "$SOURCE_TAG" '.version=$VER' package.json > temp.json && mv temp.json package.json

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm publish --access public

      - name: Cleanup
        run:
          rm ${{ github.workspace }}/.npmrc || true
